### ISSUE TITLE
500 Error when running from master/latest release 

### ISSUE THREAD

**Issue by fisoluwajana** [cloverdx/cloverdx-server-docker#5]
## Expected Behavior
Running the steps as provided in the README.md when cloning from the master branch or latest release should result in the CloverDX server  being accessible from localhost/provided host at port 8080. 

## Current Behavior
500 - Internal Server Error thrown as in screenshot
![image](https://user-images.githubusercontent.com/53525510/114070744-39f8f500-9898-11eb-89a8-dd373370e752.png)

## Possible Solution
It looks like there has been security patch in the last few releases that may be causing the issue, as using release-5-6 allows the server to be started successfully 

## Steps to Reproduce
1. Clone repo at master branch (or latest release)
```
git clone --branch release-5-6 https://github.com/cloverdx/cloverdx-server-docker.git 
```
2. Add a relevant clover.war file to the folder
3. Run gradle 
```
cd cloverdx-server-docker
gradlew
```
4. Build and Run CloverDX container
```
docker build -t cloverdx-server:latest .
docker run -d --name cloverdx --memory=3g -p 8080:8080 --mount type=bind,source=/data/cloverdx,target=/var/clover cloverdx-server:latest
```

## Context (Environment)

- Ubuntu 18.04 Bionic VM in GCP 
- Docker installed 
- Outbound internet access
- Valid clover.war added

**Comment by cirojas-spaceiq** [comment]
> ## Expected Behavior
> Running the steps as provided in the README.md when cloning from the master branch or latest release should result in the CloverDX server being accessible from localhost/provided host at port 8080.
> 
> ## Current Behavior
> 500 - Internal Server Error thrown as in screenshot ![image](https://user-images.githubusercontent.com/53525510/114070744-39f8f500-9898-11eb-89a8-dd373370e752.png)
> 
> ## Possible Solution
> It looks like there has been security patch in the last few releases that may be causing the issue, as using release-5-6 allows the server to be started successfully
> 
> ## Steps to Reproduce
> 1. Clone repo at master branch (or latest release)
> 
> ```
> git clone --branch release-5-6 https://github.com/cloverdx/cloverdx-server-docker.git 
> ```
> 
> 2. Add a relevant clover.war file to the folder
> 3. Run gradle
> 
> ```
> cd cloverdx-server-docker
> gradlew
> ```
> 
> 4. Build and Run CloverDX container
> 
> ```
> docker build -t cloverdx-server:latest .
> docker run -d --name cloverdx --memory=3g -p 8080:8080 --mount type=bind,source=/data/cloverdx,target=/var/clover cloverdx-server:latest
> ```
> 
> ## Context (Environment)
> * Ubuntu 18.04 Bionic VM in GCP
> * Docker installed
> * Outbound internet access
> * Valid clover.war added

include a web.xml in public/tomcat/conf with this

`<display-name>TestJSF</display-name>
  <welcome-file-list>
    <welcome-file>index.xhtml</welcome-file>
    <welcome-file>index.htm</welcome-file>
    <welcome-file>index.jsp</welcome-file>
    <welcome-file>default.html</welcome-file>
    <welcome-file>default.htm</welcome-file>
    <welcome-file>default.jsp</welcome-file>
  </welcome-file-list>
  <servlet>
    <servlet-name>Faces Servlet</servlet-name>
    <servlet-class>javax.faces.webapp.FacesServlet</servlet-class>
    <load-on-startup>1</load-on-startup>
  </servlet>
  <servlet-mapping>
    <servlet-name>Faces Servlet</servlet-name>
    <url-pattern>/faces/*</url-pattern>
  </servlet-mapping>
  <context-param>
    <description>State saving method: 'client' or 'server' (=default). See JSF Specification 2.5.2</description>
    <param-name>javax.faces.STATE_SAVING_METHOD</param-name>
    <param-value>client</param-value>
  </context-param>
  <context-param>
    <param-name>javax.servlet.jsp.jstl.fmt.localizationContext</param-name>
    <param-value>resources.application</param-value>
  </context-param>
  <listener>
    <listener-class>com.sun.faces.config.ConfigureListener</listener-class>
  </listener>`

this solve the issue for me

**Comment by hajekt-cloverdx** [comment]
Hello fisoluwajana,

the issue is probably caused by the update of _jsf-impl_ library (one of the security patches - for details see [CLO-20786](https://bug.cloverdx.com/browse/CLO-20786)).

The library is listed among the jars to scan for TLDs (by Tomcat during startup) in [catalina.properties](https://github.com/cloverdx/cloverdx-server-docker/blob/d3fb1faab7bb0ebfc77d85066528aa832b99b491/internal/tomcat/conf/catalina.properties#L119). If the version of the library listed in _catalina.properties_ does not match the version in clover.war, it won't be scanned for TLDs and the Server might fail to start. 

We've recently updated README.md to recommend checking out git branch (instead of master) that matches the version of CloverDX Server you want to run, which should lower the chance of inconsistency between the docker image sources and clover.war. 
However, it can still happen in some corner cases - in this case I suggest to checkout the git tag that exactly matches the CloverDX Server version, e.g. for CloverDX Server 5.6.1 checkout tag _tag-release-5-6-1_.

Best regards,
Tom
[www.cloverdx.com](https://www.cloverdx.com/)
